# Render.yaml Configuration for Portfolio Website

services:
  # Web service
  - type: web
    name: portfolio
    runtime: python
    buildCommand: pip install -r render-requirements.txt && python render_setup.py
    startCommand: gunicorn --bind 0.0.0.0:$PORT --workers 2 app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: portfolio-db
          property: connectionString
      - key: FLASK_SECRET_KEY
        generateValue: true
      - key: SESSION_SECRET
        generateValue: true
      - key: FLASK_APP
        value: app.py
      - key: FLASK_ENV
        value: production
      - key: UPLOADS_FOLDER
        value: uploads
    autoDeploy: true
    healthCheckPath: /

databases:
  - name: portfolio-db
    databaseName: portfolio
    ipAllowList: []
    plan: free